# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: PasarGuardNodeBridge/common/service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import PasarGuardNodeBridge.common.service_pb2


class NodeServiceBase(abc.ABC):

    @abc.abstractmethod
    async def Start(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.Backend, PasarGuardNodeBridge.common.service_pb2.BaseInfoResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Stop(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.Empty, PasarGuardNodeBridge.common.service_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def GetBaseInfo(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.Empty, PasarGuardNodeBridge.common.service_pb2.BaseInfoResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetLogs(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.Empty, PasarGuardNodeBridge.common.service_pb2.Log]') -> None:
        pass

    @abc.abstractmethod
    async def GetSystemStats(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.Empty, PasarGuardNodeBridge.common.service_pb2.SystemStatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetBackendStats(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.Empty, PasarGuardNodeBridge.common.service_pb2.BackendStatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetStats(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.StatRequest, PasarGuardNodeBridge.common.service_pb2.StatResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetOutboundsLatency(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.LatencyRequest, PasarGuardNodeBridge.common.service_pb2.LatencyResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetUserOnlineStats(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.StatRequest, PasarGuardNodeBridge.common.service_pb2.OnlineStatResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetUserOnlineIpListStats(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.StatRequest, PasarGuardNodeBridge.common.service_pb2.StatsOnlineIpListResponse]') -> None:
        pass

    @abc.abstractmethod
    async def SyncUser(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.User, PasarGuardNodeBridge.common.service_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def SyncUsers(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.Users, PasarGuardNodeBridge.common.service_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def SyncUsersChunked(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.UsersChunk, PasarGuardNodeBridge.common.service_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def ListRoutingRules(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.Empty, PasarGuardNodeBridge.common.service_pb2.RoutingRulesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetBalancerInfo(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.BalancerInfoRequest, PasarGuardNodeBridge.common.service_pb2.BalancerInfoResponse]') -> None:
        pass

    @abc.abstractmethod
    async def TestRoute(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.TestRouteRequest, PasarGuardNodeBridge.common.service_pb2.RouteResult]') -> None:
        pass

    @abc.abstractmethod
    async def AddRoutingRule(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.AddRoutingRuleRequest, PasarGuardNodeBridge.common.service_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def RemoveRoutingRule(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.RemoveRoutingRuleRequest, PasarGuardNodeBridge.common.service_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def OverrideBalancerTarget(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.OverrideBalancerTargetRequest, PasarGuardNodeBridge.common.service_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def ListTorLocations(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.Empty, PasarGuardNodeBridge.common.service_pb2.TorLocationsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetTorLocation(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest, PasarGuardNodeBridge.common.service_pb2.TorLocation]') -> None:
        pass

    @abc.abstractmethod
    async def CreateTorLocation(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.TorLocationSpec, PasarGuardNodeBridge.common.service_pb2.TorLocation]') -> None:
        pass

    @abc.abstractmethod
    async def UpdateTorLocation(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.TorLocationSpec, PasarGuardNodeBridge.common.service_pb2.TorLocation]') -> None:
        pass

    @abc.abstractmethod
    async def DeleteTorLocation(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.DeleteTorLocationRequest, PasarGuardNodeBridge.common.service_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def EnableTorLocation(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest, PasarGuardNodeBridge.common.service_pb2.TorLocation]') -> None:
        pass

    @abc.abstractmethod
    async def DisableTorLocation(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest, PasarGuardNodeBridge.common.service_pb2.TorLocation]') -> None:
        pass

    @abc.abstractmethod
    async def RestartTorLocation(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest, PasarGuardNodeBridge.common.service_pb2.TorLocation]') -> None:
        pass

    @abc.abstractmethod
    async def NewTorIdentity(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest, PasarGuardNodeBridge.common.service_pb2.TorLocation]') -> None:
        pass

    @abc.abstractmethod
    async def GetTorHealth(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest, PasarGuardNodeBridge.common.service_pb2.TorLocation]') -> None:
        pass

    @abc.abstractmethod
    async def RepairTorLocation(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest, PasarGuardNodeBridge.common.service_pb2.TorLocation]') -> None:
        pass

    @abc.abstractmethod
    async def TestTorLocation(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest, PasarGuardNodeBridge.common.service_pb2.TorLocation]') -> None:
        pass

    @abc.abstractmethod
    async def ForceReconcileTor(self, stream: 'grpclib.server.Stream[PasarGuardNodeBridge.common.service_pb2.Empty, PasarGuardNodeBridge.common.service_pb2.TorReconcileResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/service.NodeService/Start': grpclib.const.Handler(
                self.Start,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.Backend,
                PasarGuardNodeBridge.common.service_pb2.BaseInfoResponse,
            ),
            '/service.NodeService/Stop': grpclib.const.Handler(
                self.Stop,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.Empty,
                PasarGuardNodeBridge.common.service_pb2.Empty,
            ),
            '/service.NodeService/GetBaseInfo': grpclib.const.Handler(
                self.GetBaseInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.Empty,
                PasarGuardNodeBridge.common.service_pb2.BaseInfoResponse,
            ),
            '/service.NodeService/GetLogs': grpclib.const.Handler(
                self.GetLogs,
                grpclib.const.Cardinality.UNARY_STREAM,
                PasarGuardNodeBridge.common.service_pb2.Empty,
                PasarGuardNodeBridge.common.service_pb2.Log,
            ),
            '/service.NodeService/GetSystemStats': grpclib.const.Handler(
                self.GetSystemStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.Empty,
                PasarGuardNodeBridge.common.service_pb2.SystemStatsResponse,
            ),
            '/service.NodeService/GetBackendStats': grpclib.const.Handler(
                self.GetBackendStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.Empty,
                PasarGuardNodeBridge.common.service_pb2.BackendStatsResponse,
            ),
            '/service.NodeService/GetStats': grpclib.const.Handler(
                self.GetStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.StatRequest,
                PasarGuardNodeBridge.common.service_pb2.StatResponse,
            ),
            '/service.NodeService/GetOutboundsLatency': grpclib.const.Handler(
                self.GetOutboundsLatency,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.LatencyRequest,
                PasarGuardNodeBridge.common.service_pb2.LatencyResponse,
            ),
            '/service.NodeService/GetUserOnlineStats': grpclib.const.Handler(
                self.GetUserOnlineStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.StatRequest,
                PasarGuardNodeBridge.common.service_pb2.OnlineStatResponse,
            ),
            '/service.NodeService/GetUserOnlineIpListStats': grpclib.const.Handler(
                self.GetUserOnlineIpListStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.StatRequest,
                PasarGuardNodeBridge.common.service_pb2.StatsOnlineIpListResponse,
            ),
            '/service.NodeService/SyncUser': grpclib.const.Handler(
                self.SyncUser,
                grpclib.const.Cardinality.STREAM_UNARY,
                PasarGuardNodeBridge.common.service_pb2.User,
                PasarGuardNodeBridge.common.service_pb2.Empty,
            ),
            '/service.NodeService/SyncUsers': grpclib.const.Handler(
                self.SyncUsers,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.Users,
                PasarGuardNodeBridge.common.service_pb2.Empty,
            ),
            '/service.NodeService/SyncUsersChunked': grpclib.const.Handler(
                self.SyncUsersChunked,
                grpclib.const.Cardinality.STREAM_UNARY,
                PasarGuardNodeBridge.common.service_pb2.UsersChunk,
                PasarGuardNodeBridge.common.service_pb2.Empty,
            ),
            '/service.NodeService/ListRoutingRules': grpclib.const.Handler(
                self.ListRoutingRules,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.Empty,
                PasarGuardNodeBridge.common.service_pb2.RoutingRulesResponse,
            ),
            '/service.NodeService/GetBalancerInfo': grpclib.const.Handler(
                self.GetBalancerInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.BalancerInfoRequest,
                PasarGuardNodeBridge.common.service_pb2.BalancerInfoResponse,
            ),
            '/service.NodeService/TestRoute': grpclib.const.Handler(
                self.TestRoute,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.TestRouteRequest,
                PasarGuardNodeBridge.common.service_pb2.RouteResult,
            ),
            '/service.NodeService/AddRoutingRule': grpclib.const.Handler(
                self.AddRoutingRule,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.AddRoutingRuleRequest,
                PasarGuardNodeBridge.common.service_pb2.Empty,
            ),
            '/service.NodeService/RemoveRoutingRule': grpclib.const.Handler(
                self.RemoveRoutingRule,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.RemoveRoutingRuleRequest,
                PasarGuardNodeBridge.common.service_pb2.Empty,
            ),
            '/service.NodeService/OverrideBalancerTarget': grpclib.const.Handler(
                self.OverrideBalancerTarget,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.OverrideBalancerTargetRequest,
                PasarGuardNodeBridge.common.service_pb2.Empty,
            ),
            '/service.NodeService/ListTorLocations': grpclib.const.Handler(
                self.ListTorLocations,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.Empty,
                PasarGuardNodeBridge.common.service_pb2.TorLocationsResponse,
            ),
            '/service.NodeService/GetTorLocation': grpclib.const.Handler(
                self.GetTorLocation,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
                PasarGuardNodeBridge.common.service_pb2.TorLocation,
            ),
            '/service.NodeService/CreateTorLocation': grpclib.const.Handler(
                self.CreateTorLocation,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.TorLocationSpec,
                PasarGuardNodeBridge.common.service_pb2.TorLocation,
            ),
            '/service.NodeService/UpdateTorLocation': grpclib.const.Handler(
                self.UpdateTorLocation,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.TorLocationSpec,
                PasarGuardNodeBridge.common.service_pb2.TorLocation,
            ),
            '/service.NodeService/DeleteTorLocation': grpclib.const.Handler(
                self.DeleteTorLocation,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.DeleteTorLocationRequest,
                PasarGuardNodeBridge.common.service_pb2.Empty,
            ),
            '/service.NodeService/EnableTorLocation': grpclib.const.Handler(
                self.EnableTorLocation,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
                PasarGuardNodeBridge.common.service_pb2.TorLocation,
            ),
            '/service.NodeService/DisableTorLocation': grpclib.const.Handler(
                self.DisableTorLocation,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
                PasarGuardNodeBridge.common.service_pb2.TorLocation,
            ),
            '/service.NodeService/RestartTorLocation': grpclib.const.Handler(
                self.RestartTorLocation,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
                PasarGuardNodeBridge.common.service_pb2.TorLocation,
            ),
            '/service.NodeService/NewTorIdentity': grpclib.const.Handler(
                self.NewTorIdentity,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
                PasarGuardNodeBridge.common.service_pb2.TorLocation,
            ),
            '/service.NodeService/GetTorHealth': grpclib.const.Handler(
                self.GetTorHealth,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
                PasarGuardNodeBridge.common.service_pb2.TorLocation,
            ),
            '/service.NodeService/RepairTorLocation': grpclib.const.Handler(
                self.RepairTorLocation,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
                PasarGuardNodeBridge.common.service_pb2.TorLocation,
            ),
            '/service.NodeService/TestTorLocation': grpclib.const.Handler(
                self.TestTorLocation,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
                PasarGuardNodeBridge.common.service_pb2.TorLocation,
            ),
            '/service.NodeService/ForceReconcileTor': grpclib.const.Handler(
                self.ForceReconcileTor,
                grpclib.const.Cardinality.UNARY_UNARY,
                PasarGuardNodeBridge.common.service_pb2.Empty,
                PasarGuardNodeBridge.common.service_pb2.TorReconcileResponse,
            ),
        }


class NodeServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Start = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/Start',
            PasarGuardNodeBridge.common.service_pb2.Backend,
            PasarGuardNodeBridge.common.service_pb2.BaseInfoResponse,
        )
        self.Stop = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/Stop',
            PasarGuardNodeBridge.common.service_pb2.Empty,
            PasarGuardNodeBridge.common.service_pb2.Empty,
        )
        self.GetBaseInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/GetBaseInfo',
            PasarGuardNodeBridge.common.service_pb2.Empty,
            PasarGuardNodeBridge.common.service_pb2.BaseInfoResponse,
        )
        self.GetLogs = grpclib.client.UnaryStreamMethod(
            channel,
            '/service.NodeService/GetLogs',
            PasarGuardNodeBridge.common.service_pb2.Empty,
            PasarGuardNodeBridge.common.service_pb2.Log,
        )
        self.GetSystemStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/GetSystemStats',
            PasarGuardNodeBridge.common.service_pb2.Empty,
            PasarGuardNodeBridge.common.service_pb2.SystemStatsResponse,
        )
        self.GetBackendStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/GetBackendStats',
            PasarGuardNodeBridge.common.service_pb2.Empty,
            PasarGuardNodeBridge.common.service_pb2.BackendStatsResponse,
        )
        self.GetStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/GetStats',
            PasarGuardNodeBridge.common.service_pb2.StatRequest,
            PasarGuardNodeBridge.common.service_pb2.StatResponse,
        )
        self.GetOutboundsLatency = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/GetOutboundsLatency',
            PasarGuardNodeBridge.common.service_pb2.LatencyRequest,
            PasarGuardNodeBridge.common.service_pb2.LatencyResponse,
        )
        self.GetUserOnlineStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/GetUserOnlineStats',
            PasarGuardNodeBridge.common.service_pb2.StatRequest,
            PasarGuardNodeBridge.common.service_pb2.OnlineStatResponse,
        )
        self.GetUserOnlineIpListStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/GetUserOnlineIpListStats',
            PasarGuardNodeBridge.common.service_pb2.StatRequest,
            PasarGuardNodeBridge.common.service_pb2.StatsOnlineIpListResponse,
        )
        self.SyncUser = grpclib.client.StreamUnaryMethod(
            channel,
            '/service.NodeService/SyncUser',
            PasarGuardNodeBridge.common.service_pb2.User,
            PasarGuardNodeBridge.common.service_pb2.Empty,
        )
        self.SyncUsers = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/SyncUsers',
            PasarGuardNodeBridge.common.service_pb2.Users,
            PasarGuardNodeBridge.common.service_pb2.Empty,
        )
        self.SyncUsersChunked = grpclib.client.StreamUnaryMethod(
            channel,
            '/service.NodeService/SyncUsersChunked',
            PasarGuardNodeBridge.common.service_pb2.UsersChunk,
            PasarGuardNodeBridge.common.service_pb2.Empty,
        )
        self.ListRoutingRules = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/ListRoutingRules',
            PasarGuardNodeBridge.common.service_pb2.Empty,
            PasarGuardNodeBridge.common.service_pb2.RoutingRulesResponse,
        )
        self.GetBalancerInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/GetBalancerInfo',
            PasarGuardNodeBridge.common.service_pb2.BalancerInfoRequest,
            PasarGuardNodeBridge.common.service_pb2.BalancerInfoResponse,
        )
        self.TestRoute = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/TestRoute',
            PasarGuardNodeBridge.common.service_pb2.TestRouteRequest,
            PasarGuardNodeBridge.common.service_pb2.RouteResult,
        )
        self.AddRoutingRule = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/AddRoutingRule',
            PasarGuardNodeBridge.common.service_pb2.AddRoutingRuleRequest,
            PasarGuardNodeBridge.common.service_pb2.Empty,
        )
        self.RemoveRoutingRule = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/RemoveRoutingRule',
            PasarGuardNodeBridge.common.service_pb2.RemoveRoutingRuleRequest,
            PasarGuardNodeBridge.common.service_pb2.Empty,
        )
        self.OverrideBalancerTarget = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/OverrideBalancerTarget',
            PasarGuardNodeBridge.common.service_pb2.OverrideBalancerTargetRequest,
            PasarGuardNodeBridge.common.service_pb2.Empty,
        )
        self.ListTorLocations = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/ListTorLocations',
            PasarGuardNodeBridge.common.service_pb2.Empty,
            PasarGuardNodeBridge.common.service_pb2.TorLocationsResponse,
        )
        self.GetTorLocation = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/GetTorLocation',
            PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
            PasarGuardNodeBridge.common.service_pb2.TorLocation,
        )
        self.CreateTorLocation = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/CreateTorLocation',
            PasarGuardNodeBridge.common.service_pb2.TorLocationSpec,
            PasarGuardNodeBridge.common.service_pb2.TorLocation,
        )
        self.UpdateTorLocation = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/UpdateTorLocation',
            PasarGuardNodeBridge.common.service_pb2.TorLocationSpec,
            PasarGuardNodeBridge.common.service_pb2.TorLocation,
        )
        self.DeleteTorLocation = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/DeleteTorLocation',
            PasarGuardNodeBridge.common.service_pb2.DeleteTorLocationRequest,
            PasarGuardNodeBridge.common.service_pb2.Empty,
        )
        self.EnableTorLocation = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/EnableTorLocation',
            PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
            PasarGuardNodeBridge.common.service_pb2.TorLocation,
        )
        self.DisableTorLocation = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/DisableTorLocation',
            PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
            PasarGuardNodeBridge.common.service_pb2.TorLocation,
        )
        self.RestartTorLocation = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/RestartTorLocation',
            PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
            PasarGuardNodeBridge.common.service_pb2.TorLocation,
        )
        self.NewTorIdentity = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/NewTorIdentity',
            PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
            PasarGuardNodeBridge.common.service_pb2.TorLocation,
        )
        self.GetTorHealth = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/GetTorHealth',
            PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
            PasarGuardNodeBridge.common.service_pb2.TorLocation,
        )
        self.RepairTorLocation = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/RepairTorLocation',
            PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
            PasarGuardNodeBridge.common.service_pb2.TorLocation,
        )
        self.TestTorLocation = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/TestTorLocation',
            PasarGuardNodeBridge.common.service_pb2.TorLocationIDRequest,
            PasarGuardNodeBridge.common.service_pb2.TorLocation,
        )
        self.ForceReconcileTor = grpclib.client.UnaryUnaryMethod(
            channel,
            '/service.NodeService/ForceReconcileTor',
            PasarGuardNodeBridge.common.service_pb2.Empty,
            PasarGuardNodeBridge.common.service_pb2.TorReconcileResponse,
        )
